//go:build ignore

package main

import (
	"flag"
	"fmt"
	"os"
	"regexp"
)

func main() {
	out := flag.String("out", "kb.go", "out source")
	flag.Parse()
	if err := run(*out); err != nil {
		fmt.Fprintf(os.Stderr, "error: %v\n", err)
		os.Exit(1)
	}
}

func run(out string) error { _ = "STUB: not implemented"; return nil }

func loadKeys(keys map[rune]Key) error { _ = "STUB: not implemented"; return nil }

var (
	fixRE    = regexp.MustCompile(`,\n\s{10,}`)
	usbKeyRE = regexp.MustCompile(`(?m)^\s*DOM_CODE\((.*?), (.*?), (.*?), (.*?), (.*?), (.*?), (.*?)\)`)
)

func loadDomCodeData() (map[string][]string, error) { _ = "STUB: not implemented"; return nil, nil }

func decodeRune(s string) rune { _ = "STUB: not implemented"; return 0 }

func getCode(s string) string { _ = "STUB: not implemented"; return "" }

func addKey(keys map[rune]Key, r rune, key Key, scanCodeMap map[string][]int64, shouldPanic bool) {
	_ = "STUB: not implemented"
	return
}

var printableKeyRE = regexp.MustCompile(`\{DomCode::(.+?), \{(.+?), (.+?)\}\}`)

func loadPrintable(keys map[rune]Key, domCodeMap, domKeyMap map[string][]string, layoutBuf []byte, scanCodeMap map[string][]int64) error {
	_ = "STUB: not implemented"
	return nil
}

var domKeyRE = regexp.MustCompile(`(?m)^\s+DOM_KEY_(?:UNI|MAP)\("(.+?)",\s*(.+?),\s*(0x[0-9A-F]{4})\)`)

func loadDomKeyData() (map[string][]string, error) { _ = "STUB: not implemented"; return nil, nil }

var nonPrintableKeyRE = regexp.MustCompile(`\n\s{4}\{DomCode::(.+?), DomKey::(.+?)\}`)

func loadNonPrintable(keys map[rune]Key, domCodeMap, domKeyMap map[string][]string, layoutBuf []byte, scanCodeMap map[string][]int64) error {
	_ = "STUB: not implemented"
	return nil
}

var nameRE = regexp.MustCompile(`[A-Z][a-z]+:`)

func processKeys(keys map[rune]Key) ([]byte, []byte, error) {
	_ = "STUB: not implemented"
	return nil, nil, nil
}

var (
	domCodeVkeyFixRE = regexp.MustCompile(`,\n\s{5,}`)
	domCodeVkeyRE    = regexp.MustCompile(`(?m)^\s*\{DomCode::(.+?), (.+?)\}`)
)

func loadScanCodes(domCodeMap, domKeyMap map[string][]string, layoutBuf []byte) (map[string][]int64, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

var defineRE = regexp.MustCompile(`(?m)^#define\s+(.+?)\s+([0-9A-Fx]+)`)

func loadPosixWinKeyboardCodes() (map[string][]int64, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

var keyboardCodeRE = regexp.MustCompile(`(?m)^\s+(VKEY_.+?)\s+=\s+(.+?),`)

func loadKeyboardCodes(vkeyCodeMap map[string][]int64, lookup map[string]string, path string, pos int) error {
	_ = "STUB: not implemented"
	return nil
}

var endRE = regexp.MustCompile(`\n}`)

func extract(buf []byte, name string) []byte { _ = "STUB: not implemented"; return nil }

func grab(path string) ([]byte, error) { _ = "STUB: not implemented"; return nil, nil }

var goCodes = map[rune]string{
	'\a': `\a`,
	'\b': `\b`,
	'\f': `\f`,
	'\n': `\n`,
	'\r': `\r`,
	'\t': `\t`,
	'\v': `\v`,
	'\\': `\\`,
	'\'': `\'`,
}

const (
	chromiumSrc = "https://chromium.googlesource.com/chromium/src/+/main/"

	domUsLayoutDataH = chromiumSrc + "ui/events/keycodes/dom_us_layout_data.h?format=TEXT"

	domCodeDataInc = chromiumSrc + "ui/events/keycodes/dom/dom_code_data.inc?format=TEXT"

	domKeyDataInc = chromiumSrc + "ui/events/keycodes/dom/dom_key_data.inc?format=TEXT"

	keyboardCodesPosixH = chromiumSrc + "ui/events/keycodes/keyboard_codes_posix.h?format=TEXT"

	keyboardCodesWinH = chromiumSrc + "ui/events/keycodes/keyboard_codes_win.h?format=TEXT"

	windowsKeyboardCodesH = chromiumSrc + "third_party/blink/renderer/platform/windows_keyboard_codes.h?format=TEXT"
)

type Key struct {
	Code string

	Key string

	Text string

	Unmodified string

	Native int64

	Windows int64

	Shift bool

	Print bool
}

const hdr = `// Package kb provides keyboard mappings for Chrome DOM Keys for use with input
// events.
package kb

` + `// Code generated by gen.go. DO NOT EDIT.` + `

//go:generate go run gen.go

import (
	"runtime"
	"unicode"

	"github.com/chromedp/cdproto/input"
)

// Key contains information for generating a key press based off the unicode
// value.
//
// Example data for the following runes:
//
//	Runes      | '\r'  '\n'  | ','  '<'   | 'a'   'A'  | '\u0a07'    |
//	-----------|-------------|------------|------------|-------------|
//	Code       | "Enter"     | "Comma"    | "KeyA"     | "MediaStop" |
//	Key        | "Enter"     | ","   "<"  | "a"   "A"  | "MediaStop" |
//	Text       | "\r"  "\r"  | ","   "<"  | "a"   "A"  | ""          |
//	Unmodified | "\r"  "\r"  | ","   ","  | "a"   "a"  | ""          |
//	Native     | 0x13  0x13  | 0xbc  0xbc | 0x61  0x41 | 0x00ae      |
//	Windows    | 0x13  0x13  | 0xbc  0xbc | 0x61  0x41 | 0xe024      |
//	Shift      | false false | false true | false true | false       |
//	Print      | true  true  | true  true | true  true | false       |
type Key struct {
	// Code is the key code:
	Code string
	// Key is the key value:
	Key string
	// Text is the text for printable keys:
	Text string
	// Unmodified is the unmodified text for printable keys:
	Unmodified string
	// Native is the native scan code.
	Native int64
	// Windows is the Windows scan code.
	Windows int64
	// Shift indicates whether or not the Shift modifier should be sent.
	Shift bool
	// Print indicates whether or not the character is a printable character
	// (i.e., should a "char" event be generated).
	Print bool
}

// EncodeUnidentified encodes a keyDown, char, and keyUp sequence for an
// unidentified rune.
func EncodeUnidentified(r rune) []*input.DispatchKeyEventParams {
	// create
	keyDown := input.DispatchKeyEventParams{
		Key: "Unidentified",
		/*NativeVirtualKeyCode:  int64(r), // not sure if should be specifying the key code or not ...
		WindowsVirtualKeyCode: int64(r),*/
	}
	keyUp := keyDown
	keyDown.Type, keyUp.Type = input.KeyDown, input.KeyUp
	// printable, so create char event
	if unicode.IsPrint(r) {
		keyChar := keyDown
		keyChar.Type = input.KeyChar
		keyChar.Text = string(r)
		keyChar.UnmodifiedText = string(r)

		return []*input.DispatchKeyEventParams{&keyDown, &keyChar, &keyUp}
	}
	return []*input.DispatchKeyEventParams{&keyDown, &keyUp}
}

// Encode encodes a keyDown, char, and keyUp sequence for the specified rune.
func Encode(r rune) []*input.DispatchKeyEventParams {
	// force \n -> \r
	if r == '\n' {
		r = '\r'
	}
	// if not known key, encode as unidentified
	v, ok := Keys[r]
	if !ok {
		return EncodeUnidentified(r)
	}
	// create
	keyDown := input.DispatchKeyEventParams{
		Key:                   v.Key,
		Code:                  v.Code,
		NativeVirtualKeyCode:  v.Native,
		WindowsVirtualKeyCode: v.Windows,
	}
	if runtime.GOOS == "darwin" {
		keyDown.NativeVirtualKeyCode = 0
	}
	if v.Shift {
		keyDown.Modifiers |= input.ModifierShift
	}
	keyUp := keyDown
	keyDown.Type, keyUp.Type = input.KeyDown, input.KeyUp
	// printable, so create char event
	if v.Print {
		keyChar := keyDown
		keyChar.Type = input.KeyChar
		keyChar.Text = v.Text
		keyChar.UnmodifiedText = v.Unmodified
		// the virtual key code for char events for printable characters will
		// be different than the defined keycode when not shifted...
		//
		// specifically, it always sends the ascii value as the scan code,
		// which is available as the rune.
		keyChar.NativeVirtualKeyCode = int64(r)
		keyChar.WindowsVirtualKeyCode = int64(r)
		return []*input.DispatchKeyEventParams{&keyDown, &keyChar, &keyUp}
	}
	return []*input.DispatchKeyEventParams{&keyDown, &keyUp}
}

// DOM keys.
const (
	%s)

// Keys is the map of unicode characters to their DOM key data.
var Keys = map[rune]*Key{
	%s}
`
